### ISSUE TITLE
Some incorrect conversion in yuv420_to_yuyv422

### ISSUE THREAD

**Issue by xlievo** [awxkee/yuvutils-rs#21]
![20241211000453](https://github.com/user-attachments/assets/d4690ff5-5e42-42bc-8b39-2ea20984cc06)

![20241211000518](https://github.com/user-attachments/assets/e3bdde00-dde1-441d-af80-9b617531a304)

yuv420_to_yuyv422 api
In version 0.3.1, the right width overwriting problem can be eliminated with the following changes

yuv_to_yuy2.rs -> 110 lines
```rust
for x in _yuy2_x.. width.saturating_sub(1) as usize / 2
```
Change to
```rust
for x in _yuy2_x.. width as usize / 2
```

**Comment by awxkee** [comment]
Thanks for reporting this out!
I'll look into this

**Comment by awxkee** [comment]
Try out 0.5.11 version if this works

**Comment by awxkee** [comment]
Could you get me original YUV420 frame?

**Comment by awxkee** [comment]
Are you also using the only `yuv420_to_yuyv422` ? I'm not quite sure that actual issue is there, because I definitely cannot reproduce at the moment line fading. Also this method does not do any color blending so it quite interesting that method without color blending at all, actually does some blending.
So it will be better to check precisely your original frame at least.

**Comment by awxkee** [comment]
That's fine actually.
Could you please save just one RAW YUV420 frame and attach it here specifying its dimensions and matrix that been used?
I'm never using YUY2 everywhere so I have to perform synthetic conversions, might be something goes wrong along the way. 
At least when I'll have the frame I can do a battle test.

**Comment by awxkee** [comment]
What I've tried to:

1 - Convert your image to YUV 4:2:0
```rust
    rgb_to_yuv420(
        &mut planar_image,
        &src_bytes,
        rgba_stride as u32,
        YuvRange::Limited,
        YuvStandardMatrix::Bt601,
    )
    .unwrap();
```
2 - Convert to YUV 4:2:0 to YUY2
```rust
    let mut packed_image_mut = YuvPackedImageMut {
        yuy: BufferStoreMut::Owned(yuy2_plane),
        yuy_stride: yuy2_stride as u32,
        width,
        height,
    };
    yuv420_to_yuyv422(&mut packed_image_mut, &plane).unwrap();
```
3 - Save buffer to file
```rust
   save_yuy2_image("test_lanes_image.yuv2", packed_image_mut.width as usize, packed_image_mut.height as usize, packed_image_mut.yuy.borrow()).unwrap();
```
4 - Convert it to jpeg by ffmpeg
```bash
ffmpeg -f rawvideo -pix_fmt yuyv422 -s 1547x727 -i test_lanes_image.yuv2 output.jpg
```

This round-trip produces at least correct output on both platforms

![output](https://github.com/user-attachments/assets/3d49cec0-13d2-4f46-8d27-17e5842288f7)

5 - I've tried also my own YUY2 -> RGB
```rust
    let yuy2_img = packed_image_mut.to_fixed();
    yuyv422_to_rgb(
        &yuy2_img,
        &mut rgba,
        rgba_stride as u32,
        YuvRange::Limited,
        YuvStandardMatrix::Bt601,
    )
    .unwrap();
```

And this also looks correct to me

![converted_sharp15](https://github.com/user-attachments/assets/64f65e6f-6f21-498b-9f29-cfa6eff9b7cb)
