### ISSUE TITLE
Updated benchmark

### ISSUE THREAD

**Issue by ArtemMartus** [awxkee/yuvutils-rs#28]
#### Overview
The following table compares the performance of libyuv and yuvutils libraries for various YUV and RGB conversion operations. On my machine:
```
OS: Ubuntu 24.04.1 LTS x86_64 
Host: 80WK Lenovo Y520-15IKBN 
Kernel: 6.8.0-51-generic 
CPU: Intel i5-7300HQ (4) @ 3.500GHz 
GPU: NVIDIA GeForce GTX 1050 Mobile 
Memory: 5847MiB / 15884MiB
```
With the following patch applied:
```
diff --git a/Cargo.toml b/Cargo.toml
index 69c0bbc..a01944e 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -14,7 +14,7 @@ categories = ["multimedia::images", "multimedia::video"]
 homepage = "https://github.com/awxkee/yuvutils-rs"
 repository = "https://github.com/awxkee/yuvutils-rs"
 exclude = ["*.jpg", "assets/*", "*.png"]
-rust-version = "1.73.0"
+# rust-version = "1.73.0"
 
 [dependencies]
 num-traits = "0.2.19"
diff --git a/app/Cargo.toml b/app/Cargo.toml
index cdaa285..91e88df 100644
--- a/app/Cargo.toml
+++ b/app/Cargo.toml
@@ -6,7 +6,7 @@ edition = "2021"
 [dependencies]
 yuvutils-rs = { path = "..", features = [] }
 image = "0.25.5"
-yuv-sys = "0.3.6"
+yuv-sys = "0.3.7"
 
 [dev-dependencies]
 criterion = "0.5.1"
 ```

```
$ rustc --version                                      
rustc 1.85.0-nightly (4ba4ac612 2024-12-18)
```

#### Comparison Results running readme provided bench yuv8/16 commands on assets/main_test.jpg

| Operation | Libyuv | Yuvutils | Delta |
| --- | --- | --- | --- |
| GBR -> RGBA Limited | - | **718.18 µs** | - |
| RGB -> YUV 4:2:0 | 774.35 µs | **755.21 µs** | 19.14 µs |
| RGB10 -> YUV10 4:2:0 | - | **1.1694 ms** | - |
| RGBA -> YUV 4:2:0 | **537.25 µs** | 885.53 µs | -348.28 µs |
| RGBA -> YUV 4:2:2 | **923.51 µs** | 1.0785 ms | -155.0 µs |
| RGBA -> YUV 4:4:4 | - | **1.1996 ms** | - |
| RGBA10 -> YUV 4:4:4 | - | **1.4741 ms** | - |
| RGBA10 -> YUV10 4:2:0 | - | **1.3892 ms** | - |
| RGBA10 -> YUV10 4:2:2 | - | **1.5536 ms** | - |
| YUV 4:2:0 -> BGR24 | **918.63 µs** | - | - |
| YUV 4:2:0 -> RGB | - | **574.74 µs** | - |
| YUV 4:2:0 -> RGBA | **659.34 µs** | 674.02 µs | -14.68 µs |
| YUV 4:2:2 -> RGBA | **609.29 µs** | 776.47 µs | -167.18 µs |
| YUV 4:4:4 -> RGBA | **682.19 µs** | 900.76 µs | -218.57 µs |
| YUV10 4:2:0 -> RGB10 | - | **954.14 µs** | - |
| YUV10 4:2:0 -> RGBA10 | - | **1.2033 ms** | - |
| YUV10 4:2:0 -> RGBA8 | - | **737.88 µs** | - |
| YUV10 4:2:0 -> RGBA8 | - | **13.537 ms** | - |
| YUV10 4:2:2 -> RGBA10 | - | **1.2353 ms** | - |
| YUV10 4:2:2 -> RGBA8 | **795.95 µs** | - | - |
| YUV10 4:4:4 -> RGBA10 | - | **1.3490 ms** | - |
| YUV NV12 -> RGB | **673.27 µs** | 802.42 µs | -129.15 µs |
| YUV10 NV12 -> RGB10 | - | **2.1021 ms** | - |

#### Analysis
The comparison results show that libyuv generally outperforms yuvutils in most operations. However, yuvutils performs better in a few operations, such as GBR -> RGBA Limited and RGB -> YUV 4:2:0. It's worth noting that the performance difference between the two libraries may vary depending on the specific use case and requirements.

In general, if you need to perform a wide range of YUV and RGB conversion operations, libyuv might be a better choice due to its overall better performance. However, if you have specific requirements that favor yuvutils, it may still be a viable option.

**Comment by ArtemMartus** [comment]
@awxkee bump yuv-sys to "0.3.7". In a changelog they say that simd issues were fixed

**Comment by awxkee** [comment]
No doubts often libyuv will be faster because of

- They are using the worst available precision
- Everything is implemented for any available hardware option
- My main target is `aarch64`, so I'm playing with x86 more just for fun and even so it's faster on my devices, and sometimes faster on AWS c5.large, but I think in common its slower on c5 because I'm in the most cases haven't done AVX-512 properly as well as x86 at all sometimes.

Here is ARM results from AWS c6g.large what you could easily reverify from `dev` branch:

```bash
yuvutils YUV NV12 -> RGB
                        time:   [1.0712 ms 1.0713 ms 1.0714 ms]

yuvutils YUV NV12 -> RGBA
                        time:   [1.1699 ms 1.1700 ms 1.1702 ms]

libyuv YUV NV12 -> RGB  time:   [1.5556 ms 1.5557 ms 1.5558 ms]

yuvutils YUV 4:2:0 -> RGB
                        time:   [1.1524 ms 1.1525 ms 1.1526 ms]

libyuv YUV 4:2:0 -> BGR24
                        time:   [1.6376 ms 1.6377 ms 1.6378 ms]

yuvutils YUV 4:2:0 -> RGBA
                        time:   [1.3194 ms 1.3195 ms 1.3196 ms]

libyuv YUV 4:2:0 -> RGBA
                        time:   [1.7591 ms 1.7592 ms 1.7593 ms]

yuvutils YUV 4:2:2 -> RGBA
                        time:   [1.5833 ms 1.5834 ms 1.5835 ms]

libyuv YUV 4:2:2 -> RGBA
                        time:   [1.7113 ms 1.7114 ms 1.7115 ms]

yuvutils YUV 4:4:4 -> RGBA
                        time:   [1.4844 ms 1.4861 ms 1.4900 ms]

libyuv YUV 4:4:4 -> RGBA
                        time:   [1.6093 ms 1.6095 ms 1.6097 ms]
```

**Comment by awxkee** [comment]
Also you might try to launch with `RUSTFLAGS=-Ctarget-cpu=native` on your device because sometimes Rust runtime dispatch are making surprising things. However, I'm not really sure it will help on your device.

**Comment by awxkee** [comment]
Here is also reproducible results from AWS c5.large by using the command:
```bash
RUSTFLAGS=-Ctarget-cpu=native cargo +nightly bench --bench yuv8 --manifest-path ./app/Cargo.toml --features nightly_avx512
```

```bash
yuvutils YUV NV16 -> RGB
                        time:   [536.30 µs 537.61 µs 538.90 µs]

yuvutils YUV NV12 -> RGB
                        time:   [452.02 µs 452.18 µs 452.38 µs]

yuvutils YUV NV12 -> RGBA
                        time:   [538.95 µs 539.06 µs 539.17 µs]

libyuv YUV NV12 -> RGB  time:   [512.13 µs 512.32 µs 512.51 µs]

yuvutils YUV 4:2:0 -> RGB
                        time:   [420.38 µs 420.44 µs 420.49 µs]

libyuv YUV 4:2:0 -> BGR24
                        time:   [778.44 µs 778.58 µs 778.72 µs]

yuvutils YUV 4:2:0 -> RGBA
                        time:   [506.79 µs 506.89 µs 506.99 µs]

libyuv YUV 4:2:0 -> RGBA
                        time:   [550.82 µs 551.01 µs 551.18 µs]

yuvutils YUV 4:2:2 -> RGBA
                        time:   [510.09 µs 510.22 µs 510.36 µs]

libyuv YUV 4:2:2 -> RGBA
                        time:   [494.17 µs 494.37 µs 494.57 µs]

yuvutils YUV 4:4:4 -> RGBA
                        time:   [533.77 µs 533.88 µs 534.00 µs]

libyuv YUV 4:4:4 -> RGBA
                        time:   [503.26 µs 503.42 µs 503.58 µs]
```

Consider half of methods here actually are lacking AVX-512 from my side.
But again, it wouldn't be feasible to reimplement every available x86 legacy cpu just to make it faster than libyuv in 100% cases.

**Comment by awxkee** [comment]
I got it. libyuv still reports huge losses on some paths on my home machine on Windows. However, for x86 linux looks like dispatch is better.

**Comment by ArtemMartus** [comment]
Alright, I see your point. Seems you've done a nice optimization work on that!
